### ISSUE TITLE
wijziging cover afbeelding

### ISSUE THREAD

**Issue by hans2103** [hans2103/uitgeverijVesuvius#4]
ontvangen van @harryjkraaij via de mail:

> Kun je de afbeelding van het Kuitertboek op de Vesuviussite omwisselen voor de bijlage?

[Gert J. Peelen, Spreken over boven - Harry Kuitert - Biografie  .pdf](https://github.com/hans2103/uitgeverijVesuvius/files/592302/Gert.J.Peelen.Spreken.over.boven.-.Harry.Kuitert.-.Biografie.pdf)

**Comment by hans2103** [comment]
@harryjkraaij afbeelding gewijzigd. 
Je kunt deze issue sluiten bij akkoord.

**Comment by harryjkraaij** [comment]
Dag Hans,

Kun je nog twee dingen doen:
bij het Kuitert -boek zetten: verschijnt 24 november.
Maak hem maar alvast bestelbaar via de webwinkel.

Het boek van Vermeer is binnen.
Die mag ook bestelbaar zijn via de webwinkel.

**Comment by hans2103** [comment]
extra vragen gekopieerd naar #5 en #6.
Deze staan los van dit issue
