### ISSUE TITLE
wijzigen Kuitert-boek

### ISSUE THREAD

**Issue by hans2103** [hans2103/uitgeverijVesuvius#5]
> bij het Kuitert -boek zetten: verschijnt 24 november.
Maak hem maar alvast bestelbaar via de webwinkel.

**Comment by hans2103** [comment]
@harryjkraaij wat is de link naar het product in de winkel? Ik kon hem niet vinden.

**Comment by harryjkraaij** [comment]
Ja, dat is natuurlijk wel handig....:
https://my.ecwid.com/cp/CP.html#product:mode=edit&id=75386036&return=products:term%3Dspreken

productcode 75386036

**Comment by hans2103** [comment]
issue moet open blijven, omdat ik de url nog niet verwerkt heb

**Comment by hans2103** [comment]
@harryjkraaij als ik deze link verwerk komt men op Ecwid uit. Dat lijkt me niet de bedoeling. 
Wat is de url op www.vuuniversitypress.com?

**Comment by harryjkraaij** [comment]
http://vuuniversitypress.com/catalogus#!/Spreken-over-boven-Harry-Kuitert-een-biografie/p/75386036

**Comment by hans2103** [comment]
@harryjkraaij knop toegevoegd
