### ISSUE TITLE
toevoegen bestellink boek van Vermeer

### ISSUE THREAD

**Issue by hans2103** [hans2103/uitgeverijVesuvius#6]
> Het boek van Vermeer is binnen.
Die mag ook bestelbaar zijn via de webwinkel.

**Comment by hans2103** [comment]
Wat is de link naar het product in de winkel?

**Comment by harryjkraaij** [comment]
https://my.ecwid.com/cp/CP.html#product:mode=edit&id=75386037&return=products:term%3Dspreken

productcode 75386037

**Comment by harryjkraaij** [comment]
http://vuuniversitypress.com/catalogus#!/Ontwikkelingshulp-ja-Een-pleidooi/p/75386037
